-- MySQL Script generated by MySQL Workbench
-- Wed Nov 24 16:01:45 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_dlog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_dlog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_dlog` DEFAULT CHARACTER SET utf8 ;
USE `db_dlog` ;

-- -----------------------------------------------------
-- Table `db_dlog`.`tbmodelo_fiscal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dlog`.`tbmodelo_fiscal` (
  `id` INT NOT NULL,
  `nome` INT(3) NULL,
  `data_criacao` DATETIME NULL,
  `flg_ativo` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dlog`.`tbinfo_operacional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dlog`.`tbinfo_operacional` (
  `id` INT NOT NULL,
  `prazo_entrega_adicional` INT(3) NULL,
  `redespacho_correio` TINYINT(1) NULL,
  `media_envio_dia` INT NULL,
  `data_cadastro` DATETIME NULL,
  `tbmodelo_fiscal_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tbmodelo_fiscal_id`),
  INDEX `fk_tbinfo_operacional_tbmodelo_fiscal1_idx` (`tbmodelo_fiscal_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbinfo_operacional_tbmodelo_fiscal1`
    FOREIGN KEY (`tbmodelo_fiscal_id`)
    REFERENCES `db_dlog`.`tbmodelo_fiscal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dlog`.`tbapi_dlog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dlog`.`tbapi_dlog` (
  `id` INT NOT NULL,
  `login` VARCHAR(30) NULL,
  `token` VARCHAR(255) NULL,
  `flg_ativo` TINYINT(1) NULL,
  `data_atualizacao` DATETIME NULL,
  `data_cadastro` DATETIME NULL,
  `user_id_alteracao` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dlog`.`tbempresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dlog`.`tbempresa` (
  `id` INT NOT NULL,
  `nome_fantasia` VARCHAR(100) NULL,
  `razao_social` VARCHAR(150) NULL,
  `cnpj` INT(14) NULL,
  `incricao_estadual` INT(9) NULL,
  `endereco` VARCHAR(100) NULL,
  `numero` INT(5) NULL,
  `cep` VARCHAR(9) NULL,
  `bairro` VARCHAR(60) NULL,
  `cidade` VARCHAR(60) NULL,
  `complemento` VARCHAR(100) NULL,
  `uf` VARCHAR(2) NULL,
  `tbinfo_operacional_id` INT NOT NULL,
  `tbapi_dlog_id` INT NOT NULL,
  `flg_ativo` TINYINT(1) NULL,
  `data_criacao` DATETIME NULL,
  `data_atualizacao` DATETIME NULL,
  PRIMARY KEY (`id`, `tbinfo_operacional_id`, `tbapi_dlog_id`),
  INDEX `fk_tbempresa_tbinfo_operacional1_idx` (`tbinfo_operacional_id` ASC) VISIBLE,
  INDEX `fk_tbempresa_tbapi_dlog1_idx` (`tbapi_dlog_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbempresa_tbinfo_operacional1`
    FOREIGN KEY (`tbinfo_operacional_id`)
    REFERENCES `db_dlog`.`tbinfo_operacional` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbempresa_tbapi_dlog1`
    FOREIGN KEY (`tbapi_dlog_id`)
    REFERENCES `db_dlog`.`tbapi_dlog` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dlog`.`tbdepartamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dlog`.`tbdepartamento` (
  `id` INT NOT NULL,
  `nome` VARCHAR(50) NULL,
  `data_criacao` DATETIME NULL,
  `flg_ativo` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dlog`.`tbcontato_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dlog`.`tbcontato_empresa` (
  `id` INT NOT NULL,
  `nome` VARCHAR(100) NULL,
  `ddd` INT(3) NULL,
  `telefone` INT(15) NULL,
  `email` VARCHAR(100) NULL,
  `id_usuario` INT NULL,
  `flg_ativo` TINYINT(1) NULL,
  `data_cadastro` DATETIME NULL,
  `tbempresa_id` INT NOT NULL,
  `tbdepartamento_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tbempresa_id`, `tbdepartamento_id`),
  INDEX `fk_tbcontato_empresa_tbempresa1_idx` (`tbempresa_id` ASC) VISIBLE,
  INDEX `fk_tbcontato_empresa_tbdepartamento1_idx` (`tbdepartamento_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbcontato_empresa_tbempresa1`
    FOREIGN KEY (`tbempresa_id`)
    REFERENCES `db_dlog`.`tbempresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbcontato_empresa_tbdepartamento1`
    FOREIGN KEY (`tbdepartamento_id`)
    REFERENCES `db_dlog`.`tbdepartamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dlog`.`tbdados_cadastrais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dlog`.`tbdados_cadastrais` (
  `id` INT NOT NULL,
  `tbempresa_id` INT NOT NULL,
  `flg_matriz` TINYINT(1) NULL,
  `flg_fornecedor` TINYINT(1) NULL,
  `flg_cliente` TINYINT(1) NULL,
  `idpai_tomador` INT NULL,
  `idpai_expedidor` INT NULL,
  `idpai_grupo` INT NULL,
  `data_criacao` DATETIME NULL,
  `data_atualizacao` DATETIME NULL,
  `flg_ativo` TINYINT(1) NULL,
  `user_id_alteracao` INT NULL,
  PRIMARY KEY (`id`, `tbempresa_id`),
  INDEX `fk_tbdados_cadastrais_tbempresa1_idx` (`tbempresa_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbdados_cadastrais_tbempresa1`
    FOREIGN KEY (`tbempresa_id`)
    REFERENCES `db_dlog`.`tbempresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dlog`.`tbusuario_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dlog`.`tbusuario_empresa` (
  `id` INT NOT NULL,
  `nome` VARCHAR(50) NULL,
  `sobrenome` VARCHAR(50) NULL,
  `data_nascimento` DATE NULL,
  `ddd` INT(2) NULL,
  `telefone` INT(12) NULL,
  `email` VARCHAR(50) NULL,
  `flg_ativo` TINYINT(1) NULL,
  `data_criacao` DATETIME NULL,
  `tbdados_cadastrais_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tbdados_cadastrais_id`),
  INDEX `fk_tbusuario_tbdados_cadastrais1_idx` (`tbdados_cadastrais_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbusuario_tbdados_cadastrais1`
    FOREIGN KEY (`tbdados_cadastrais_id`)
    REFERENCES `db_dlog`.`tbdados_cadastrais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dlog`.`tbmenu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dlog`.`tbmenu` (
  `id` INT NOT NULL,
  `id_pai` INT NULL,
  `nome` VARCHAR(50) NULL,
  `descricao` VARCHAR(255) NULL,
  `flg_ativo` TINYINT(1) NULL,
  `data_criacao` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dlog`.`tbmenu_acesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dlog`.`tbmenu_acesso` (
  `id` INT NOT NULL,
  `id_pai` INT NULL,
  `nome` VARCHAR(50) NULL,
  `descricao` VARCHAR(255) NULL,
  `flg_ativo` TINYINT(1) NULL,
  `data_criacao` DATETIME NULL,
  `tbdepartamento_id` INT NOT NULL,
  `tbusuario_empresa_id` INT NOT NULL,
  `tbmenu_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tbdepartamento_id`, `tbusuario_empresa_id`, `tbmenu_id`),
  INDEX `fk_tbmenu_acesso_tbdepartamento1_idx` (`tbdepartamento_id` ASC) VISIBLE,
  INDEX `fk_tbmenu_acesso_tbusuario_empresa1_idx` (`tbusuario_empresa_id` ASC) VISIBLE,
  INDEX `fk_tbmenu_acesso_tbmenu1_idx` (`tbmenu_id` ASC) VISIBLE,
  CONSTRAINT `fk_tbmenu_acesso_tbdepartamento1`
    FOREIGN KEY (`tbdepartamento_id`)
    REFERENCES `db_dlog`.`tbdepartamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbmenu_acesso_tbusuario_empresa1`
    FOREIGN KEY (`tbusuario_empresa_id`)
    REFERENCES `db_dlog`.`tbusuario_empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbmenu_acesso_tbmenu1`
    FOREIGN KEY (`tbmenu_id`)
    REFERENCES `db_dlog`.`tbmenu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
